# Generated by Django 5.1.1 on 2024-10-09 10:02

import apps.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='формат телеграм ID: 1234567890 или -1234567890', max_length=20, validators=[apps.validators.is_valid_telegram_id, django.core.validators.MinLengthValidator(7)], verbose_name='Телеграм ID'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фотография')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Фотографию',
                'verbose_name_plural': 'Фотографии',
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.DeleteModel(
            name='Memory',
        ),
    ]
