# Generated by Django 5.1.1 on 2024-10-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_user_telegram_id_photo_delete_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='%Y/%m', verbose_name='Фотография'),
        ),
    ]
