services:
  postgres:
      image: postgres:17
      container_name: postgres
      environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      ports:
        - "${DB_PORT}:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django
    command: >
      sh -c "sh /app/start.sh && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "${API_PORT}:8000"
    volumes:
      - ./backend/:/app/
    env_file:
      - .env
    environment:
        DB_HOST: postgres
    depends_on:
      - postgres


volumes:
  postgres_data:
