name: linter-check

on:
  push:
    branches: [ "*" ]

  pull_request:
      branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Setup-python
        uses: actions/setup-python@v5

      - name: Install dependecies
        run: pip install poetry && poetry install

      - name: run
        run: poetry run ruff check .
